server:
  port: 8080
  servlet:
    application-display-name: ${spring.application.name}
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
  application:
    name: hexagonal-spring
  datasource:
    name: ${spring.application.name}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      show_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
